name: Study Cypress Two

on:
  push:
    branches:
      - main
    paths:
      - 'study-cypress-two/**.js'
      - 'study-cypress-two/**.json'
      - 'study-cypress-two/**.yml'

jobs:
  study-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.7.0

      - name: Install dependencies
        run: npm install
        working-directory: ./study-cypress-two

      - name: Run Cypress tests
        run: npm run cypress:headless
        working-directory: ./study-cypress-two

      - name: Run Cypress tests integration Cloud Cypress
          # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          start: npm start
          wait-on: 'http://localhost:3000' # Waits for above
          # Records to Cypress Cloud 
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          record: true
          parallel: true # Runs test in parallel using settings above
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        # working-directory: ./study-cypress-two