name: Study Cypress Two

on:
  push:
    branches:
      - main
    paths:
      - 'study-cypress-two/**.js'
      - 'study-cypress-two/**.json'
      - 'study-cypress-two/**.yml'

jobs:
  study-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.7.0

      - name: Install dependencies
        run: npm install
        working-directory: ./study-cypress-two

      - name: Run Cypress tests
        run: npm run cypress:headless
        working-directory: ./study-cypress-two

      - name: Run Cypress tests integration Cloud Cypress
        run: npm run cypress:integration
        working-directory: ./study-cypress-two