name: Study Cypress

on:
  push:
    branches:
      - main
    paths:
      - 'study-cypress/**.js'
      - 'study-cypress/**.json'
      - 'study-cypress/**.yml'

jobs:
  study-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.7.0

      - name: Install dependencies
        run: npm install
        working-directory: ./study-cypress

      - name: Run Cypress tests
        run: npm run cypress:headless
        working-directory: ./study-cypress